server:
  port: 8081  # Puerto donde correrá el microservicio buscador

spring:
  application:
    name: microservicio-buscador

  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: PifaHsmeSfDMmOmkQmDuIZwcjCpVLICw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Crea las tablas automáticamente si no existen
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-production-5a1a.up.railway.app/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
